# -*- coding: utf-8 -*-
"""Untitled102.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l_DvsZuBh3r6S_qka4Esb8Y9GICuVJ4_
"""

from fastapi import FastAPI

from flask import Flask

from google.colab import files

import pandas as pd

import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"

data = pd.read_csv(url)

data

#unrealistic random shit

data['tip_precent']= 100*data['tip']/data['total_bill']

data.to_csv("naiadataframe.csv", index = False)

import pandas as pd

files.download("naiadataframe.csv")



#com we will wrap this shit up all together in a functio

#now we actually have the particular kind of url , from which we would like to make a couple of modifications time to time
def tipcalculationautomatic():
  url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
  data = pd.read_csv(url)
  #this is total percent
  data['tip_precent'] = data['tip'] * 100/ data['total_bill']
  data.to_csv('modifieddataframe.csv')
  files.download('modifieddataframe.csv')
  return (" ")

tipcalculationautomatic()

tipcalculationautomatic()